// src/app/docs/api/page.tsx
import Link from "next/link";

export default function ApiOverviewPage() {
  return (
    <div className="space-y-8">
      <header>
        <p className="text-xs font-semibold tracking-[0.2em] text-emerald-400 uppercase">
          API Overview
        </p>
        <h1 className="mt-2 text-3xl font-semibold tracking-tight text-slate-50">
          MarketMind APIs
        </h1>
        <p className="mt-3 text-sm text-slate-400">
          MarketMind exposes multiple surfaces for integrating the meta-learning
          runtime with your own infrastructure. Start with REST for control-plane
          operations, then move to gRPC or WebSockets for low-latency data and
          execution.
        </p>
      </header>

      <section className="grid gap-6 md:grid-cols-3">
        <article className="rounded-xl border border-white/10 bg-slate-900/40 p-4">
          <h2 className="text-base font-semibold text-slate-50">REST API</h2>
          <p className="mt-2 text-xs text-slate-400">
            Control pipelines, strategies, and configuration via a familiar HTTP+JSON
            interface.
          </p>
          <Link
            href="/docs/api/rest"
            className="mt-3 inline-flex items-center text-xs font-medium text-emerald-400 hover:text-emerald-300"
          >
            View REST endpoints &rarr;
          </Link>
        </article>

        <article className="rounded-xl border border-white/10 bg-slate-900/40 p-4">
          <h2 className="text-base font-semibold text-slate-50">gRPC API</h2>
          <p className="mt-2 text-xs text-slate-400">
            High-throughput, low-latency access to signals, decisions, and telemetry
            from typed clients.
          </p>
          <Link
            href="/docs/api/grpc"
            className="mt-3 inline-flex items-center text-xs font-medium text-emerald-400 hover:text-emerald-300"
          >
            View gRPC contracts &rarr;
          </Link>
        </article>

        <article className="rounded-xl border border-white/10 bg-slate-900/40 p-4">
          <h2 className="text-base font-semibold text-slate-50">WebSocket API</h2>
          <p className="mt-2 text-xs text-slate-400">
            Stream live events, signals, and metrics into browsers or lightweight
            clients.
          </p>
          <Link
            href="/docs/api/websocket"
            className="mt-3 inline-flex items-center text-xs font-medium text-emerald-400 hover:text-emerald-300"
          >
            View WebSocket streams &rarr;
          </Link>
        </article>
      </section>

      <section className="border-t border-white/10 pt-6 text-sm text-slate-400">
        <p>
          For detailed schema and autogenerated client bindings, see the{" "}
          <a
            href="https://marketmind-docs.readthedocs.io/en/latest/"
            className="text-emerald-400 hover:text-emerald-300"
          >
            full technical reference
          </a>
          .
        </p>
      </section>
    </div>
  );
}
